### ISSUE TITLE
抽奖运行时其余按钮需不可点击

### ISSUE THREAD

**Issue by ytc1989** [fouber/lottery#6]
**程序在点击开始按钮后，应把其余按钮给禁止掉。**

比如你选了抽1人，然后点击开始按钮，如果不禁止其余按钮，你再点5人，最终结果会显示5个结果，这个是不符合实际预期的。

重置按钮同理。

**Comment by fouber** [comment]
我考虑到在使用过程中可能一开始人数选错了，需要修改，所以留下了这个修改空间。

**Comment by sunrong1990** [comment]
这不是问题
